public without sharing class Optiva_NPD_Application_Wrapper {
    public String project_sf_code;	//1212121
	public String project_title;	//ABC XYZ
	public String created_by;	//Ajeet
	public String creation_date;	//8/24/2021
	public String project_type;	//External
	public String project_category;	//Natural Colour
	public String opp_type_int;	//Sales
	public String opp_sub_type_sales;	//Application
	public String cust_code;	//C11023
	public String end_use_cat;	//end-use_category
	public String end_use_appli;	//end-use_app
	public String annual_vol;	//50000
	public Double business_potent_val;	//78.9
	public String curr_year_vol;	//890000
	public String cust_target_price;	//500000
	public String target_date;	//8/24/2021
	public String curr_type;	//Euro
	public String confectionary_type;	//Sugar boiled candy
	public Decimal final_fat;	//12
	public String first_smpe_due_date;	//8/24/2021
	public Decimal flavor_ciu;	//450
	public String flavor_legal_stat;	//Verified
	public String solubility;	//solubility
	public String sugar;	//brown_sugar
	public String opp_closedate;	//8/24/2021
}